<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net9.0-windows10.0.19041.0</TargetFrameworks>

		<OutputType>Exe</OutputType>
		<RootNamespace>TabletController.Collect</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>BrandStore Collect</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.itab.collect</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.2</ApplicationDisplayVersion>
		<ApplicationVersion>3</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">30.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
		<MauiXamlEnableCompile>true</MauiXamlEnableCompile>
		<AndroidSigningKeyStore>pivotal.keystore</AndroidSigningKeyStore>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-android|AnyCPU'">
	  <AndroidKeyStore>True</AndroidKeyStore>
	  <AndroidSigningStorePass>ShinyRock2</AndroidSigningStorePass>
	  <AndroidSigningKeyAlias>pivotal</AndroidSigningKeyAlias>
	  <AndroidSigningKeyPass>ShinyRock2</AndroidSigningKeyPass>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-android|AnyCPU'">
	  <AndroidKeyStore>True</AndroidKeyStore>
	  <AndroidSigningStorePass>ShinyRock2</AndroidSigningStorePass>
	  <AndroidSigningKeyAlias>pivotal</AndroidSigningKeyAlias>
	  <AndroidSigningKeyPass>ShinyRock2</AndroidSigningKeyPass>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#231F20" BaseSize="512,512" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#231F20" BaseSize="167,78" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
		
		<!-- Images -->
		<MauiImage Include="Resources\Images\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.8" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TabletController.Core\TabletController.Core.csproj" />
		<ProjectReference Include="..\TabletController.Hardware\TabletController.Hardware.csproj" />
		<ProjectReference Include="..\TabletController.Shared\TabletController.Shared.csproj" />
	</ItemGroup>

</Project>
